Config_path: "./Configs/path.yaml"
openTI_root: &path_root C:/Users/xyluo25/anaconda3_workspace/001_GitHub/OpenTI/OpenTI/
SUMO_root: &sumo C:/Users/xyluo25/anaconda3_workspace/001_GitHub/OpenTI/sumo

LibSignal:
    root_path: !join [*path_root, support_libsignal/LibSignal/LibSignal]
    log_example: !join [*path_root, support_libsignal/LibSignal/LibSignal/data/output_data/tsc/cityflow_dqn/cityflow1x1/0/logger/2023_10_10-13_00_07_DTL.log]
    tsc_root: !join [*path_root, support_libsignal/LibSignal/LibSignal/data/output_data/tsc/]
    tsc_base: !join [*path_root, support_libsignal/LibSignal/LibSignal/configs/tsc/base.yml]

Demand:
    example: !join [*path_root, pivotalAgent/fig/demand.png]

DLSim:
    work_dic: !join [*path_root, "pivotalAgent/AugmentUtils/simulation/simulate"]
    simulate_base: !join [*path_root, pivotalAgent/AugmentUtils/simulation/simulate/]

SUMO_PATH: *sumo # your sumo path, x/x/x/sumo

SUMO_PIPLINE: !join [*path_root, pivotalAgent/AugmentUtils/one_click_SUMO/simulate_pipline.py]

showMap:
    targetMapPng: !join [*path_root, pivotalAgent/Data/maps/target_map.png]
    htmlPath : !join [*path_root, pivotalAgent/Data/maps/target_map.html]

OSM_BASE: !join [*path_root, pivotalAgent/Data/download/OSM/]

FIlter_Store_Base: !join [*path_root, pivotalAgent/Data/netfilter/output/]
